object form_Details_Worker: Tform_Details_Worker
  Left = 0
  Top = 0
  Caption = #1055#1086#1076#1088#1086#1073#1085#1086#1089#1090#1080' '#1089#1086#1090#1088#1091#1076#1085#1080#1082#1072
  ClientHeight = 306
  ClientWidth = 286
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object label_name: TLabel
    Left = 104
    Top = 51
    Width = 66
    Height = 13
    Caption = 'label_name'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Verdana'
    Font.Style = []
    ParentFont = False
  end
  object label_surname: TLabel
    Left = 104
    Top = 35
    Width = 84
    Height = 13
    Caption = 'label_surname'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Verdana'
    Font.Style = []
    ParentFont = False
  end
  object label_role: TLabel
    Left = 104
    Top = 78
    Width = 56
    Height = 13
    Caption = 'label_role'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Verdana'
    Font.Style = []
    ParentFont = False
  end
  object label_dob: TLabel
    Left = 104
    Top = 104
    Width = 55
    Height = 13
    Caption = 'label_dob'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Verdana'
    Font.Style = []
    ParentFont = False
  end
  object label_exp: TLabel
    Left = 104
    Top = 123
    Width = 55
    Height = 13
    Caption = 'label_exp'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Verdana'
    Font.Style = []
    ParentFont = False
  end
  object label_id: TLabel
    Left = 104
    Top = 16
    Width = 44
    Height = 13
    Caption = 'label_id'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Verdana'
    Font.Style = []
    ParentFont = False
  end
  object label_login: TLabel
    Left = 104
    Top = 152
    Width = 50
    Height = 13
    Caption = 'label_login'
  end
  object label_password: TLabel
    Left = 104
    Top = 171
    Width = 74
    Height = 13
    Caption = 'label_password'
  end
end
